Переписал SessionData для динамической генерации сообщений, добавил функционал next, last, skip
Trickster22/DiscordMeetingBot pull request #1
Opened 2024-09-27 14:26 UTC by Max-Person

Господи (Миша), смерджи мой реквест пожалуйста

2024-09-27 15:07 UTC, Trickster22 requested changes
Можешь рассказать пожалуйста как ты видишь работу бота?
Просто у тебя получается больше как по мне лишней нагрузки на систему по типу каждый раз получать лист и шафлить его при каждом выборе из него. Так же не понял прикол с создание Messagebuider каждый раз когда выбираешь следующего, т.е. зачем-то сообщение с нуля генерируется.

2024-09-27 15:07 UTC, Trickster22 commented on src/main/java/org/example/SessionData.java
> +    private final Deque<Member> nextQueue = new ArrayDeque<>();
Почему дек решил использовать

2024-09-27 15:07 UTC, Trickster22 commented on src/main/java/org/example/ChannelEventListener.java
> +        SessionData.UpdateResult updateResult = sessionData.update(getCurrentMembers(event.getGuild()));
то есть при каждом нажатии кнопки ты будешь получать список всех участников в канале?

2024-09-27 15:07 UTC, Trickster22 commented on src/main/java/org/example/SessionData.java
> +            Collections.shuffle(notSpokenMembers);
и ты каждый раз при выборе следующего человека из списка шафлишь список?

2024-09-27 15:07 UTC, Trickster22 commented on src/main/java/org/example/SessionData.java
> +        MessageBuilder messageBuilder = new MessageBuilder();
Чем тебе не нравился вариант хранить для сессии сообщение и просто добавлять туда нового участника или прощание?

2024-09-27 15:07 UTC, Trickster22 commented on src/main/java/org/example/ChannelEventListener.java
> -    public void onGuildVoiceUpdate(GuildVoiceUpdateEvent event) {
почему убрал

2024-09-27 20:20 UTC, Max-Person commented on src/main/java/org/example/SessionData.java
> +    private final Deque<Member> nextQueue = new ArrayDeque<>();
Быстро записывать в конец и убирать с начала
Можно было бы Queue, но Deque удобнее как-то, вдруг зачем-нибудь пригодится с конца тоже убирать

2024-09-27 20:20 UTC, Max-Person commented on src/main/java/org/example/ChannelEventListener.java
> +        SessionData.UpdateResult updateResult = sessionData.update(getCurrentMembers(event.getGuild()));
yes

2024-09-27 20:21 UTC, Max-Person commented on src/main/java/org/example/SessionData.java
> +            Collections.shuffle(notSpokenMembers);
yes

2024-09-27 20:22 UTC, Max-Person commented on src/main/java/org/example/SessionData.java
> +        MessageBuilder messageBuilder = new MessageBuilder();
Да можно в принципе, но это лишнее хранение того, что можно вычислить
Я любитель вычисляемых данных - в них меньше шансов ошибиться с алгоритмом и т.п. Хранить можно, если вычислять долго/сложно - а здесь с ботом, который итерируется по максимум 15-ти значениям о таком речи не идет)

2024-09-27 20:23 UTC, Max-Person commented on src/main/java/org/example/ChannelEventListener.java
> -    public void onGuildVoiceUpdate(GuildVoiceUpdateEvent event) {
ну потому что не нужно уже

2024-09-27 20:32 UTC, Max-Person commented
Блин ну Миш)
О какой "лишней нагрузке на систему" идет речь, когда нужно просто узнать участников канала (максимум 15 чел), и их зашафлить. Это все миллисекунды времени.
При этом такое решение "за бесплатно" (без лишего кода) дает тебе корректный учет всех участников, которые могут уходить-приходить как хотят, а также например динамическую смену имен в очереди (если кто-то резко решит поменять ник), как приятный бонус.
Так же и с созданием сообщения - я выше в принципе написал, но кому какая разница, сделаешь ты 15 конкатенаций строки за нажатие или 1.

В общем, я не понимаю, зачем оптимизировать бота, который ворочает АЖ 15 значений на одно нажатие кнопки - готов поспорить на отправку запроса из дискорда и обратно уходит больше времени чем на всю обработку вместе взятую

2024-09-28 06:02 UTC, Max-Person commented
upd: Но справедливости ради да, список можно и не шафлить каждый раз - можно просто брать участника по рандомному  индексу, это наверное было бы правильнее

2024-09-29 15:46 UTC, Trickster22 commented
Ну этот бот может использоваться не только нашей командой, он пригодится любым людям, которые хотят получать рандомно очередь выступающих.  Максимальное число участников в голосовом канале 200 и получается ты 200 раз будешь брать участников, 200 раз его шафлить (каждый раз он меньше будет) и 200 раз с нуля генерить сообщение. Мне кажется, это не лучший подход.
Это норм если ты раз написал бота онли для нашей команды и не трогаешь его потом, но я ориентировался на более универсальный проект. ИМХО Лучше сразу оптимизировано делать, чем потом переделывать, когда понадобиться.

2024-09-29 15:48 UTC, Trickster22 commented
предлагаю тогда мейн ветку оставить под твой вариант, а в отдельной будет мой. develop и feature)

2024-09-30 07:22 UTC, Max-Person commented
> Максимальное число участников в голосовом канале 200 и получается ты 200 раз будешь брать участников, 200 раз его шафлить (каждый раз он меньше будет) и 200 раз с нуля генерить сообщение. Мне кажется, это не лучший подход.

Почему? Я понимаю как бы, на слух это звучит как много действий, но по факту это все пыль на ветру - для любого компа проитерироваться по списку 200 элементов можно хоть тысячу раз на каждое нажатие, и это все займет миллисекунды. То же самое с конкатенацией выражений.
Хз, мне кажется плюсы я описал, а минусы только в отсутствии оптимизации, которая кмк здесь и не понадобится никогда.

2024-09-30 07:25 UTC, Max-Person commented
Ну штуку с ненужностью шафла (о которой выше говорил) я еще поправлю, да

2024-09-30 07:27 UTC, Max-Person commented
> предлагаю тогда мейн ветку оставить под твой вариант, а в отдельной будет мой. develop и feature)

Ну ты делай как хочешь, проект все таки твой)
Но если ты говоришь мейн ветку оставить под этот вариант, ты значит смерджишь?

2024-09-30 08:06 UTC, merged